Main:
  list-mode: lax # allow unless explicitely denied
  files:
    - $all
  allow:
    - $gostd
    - github.com/vtpl1/avsdk
  deny:
    - io/ioutil: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
    - reflect: Please don't use reflect package    

